version: "3.7"

services:
  app:
    build: .
    ports:
      - "$FILEUPLOADER_REAL_PORT:443"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FILEUPLOADER_HOSTNAME
      - FILEUPLOADER_REAL_PORT
      - FILEUPLOADER_TOP_REDIRECT
      - MICRO_QR_URL
    volumes:
      - ./log/:/app/log/
      - upload_file:/app/files/
      - ./.env:/app/.env
    restart: always
    stdin_open: true
    tty: true
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=main
    volumes:
      - mysql_file:/var/lib/mysql
    restart: always

volumes:
  mysql_file:
  upload_file:
