version: "3.7"

services:
  app:
    build: .
    ports:
      - 4000:443
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FILEUPLOADER_HOSTNAME
      - FILEUPLOADER_CERT_PATH
    volumes:
      - ./log/:/app/log/
      - "$FILEUPLOADER_CERT_PATH:/etc/cert/"
    restart: always
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=main
    volumes:
      - mysql_file:/var/lib/mysql
    restart: always

volumes:
  mysql_file:
